### ISSUE TITLE
CSV機能を追加する

### ISSUE THREAD

**Issue by mzkmnk** [mzkmnk/TestCraft#1]
# 概要
12月と冬休みで作成してくれたcsv機能を追加する。

**Comment by mzkmnk** [comment]
https://magazine.techacademy.jp/magazine/16113

**Comment by mzkmnk** [comment]
python manage.py loaddata  api/fixtures/fixture.json

**Comment by mzkmnk** [comment]
https://yu-nix.com/archives/django-create/

**Comment by mzkmnk** [comment]
class CsvUploadSchema(Schema):
    csv_file: UploadedFile

**Comment by mzkmnk** [comment]
from django.core.files.uploadedfile import UploadedFile

**Comment by mzkmnk** [comment]
class CsvUploadSchema(Schema):
    csv_file: UploadedFile
    class Config:
        arbitrary_types_allowed = True

**Comment by mzkmnk** [comment]
https://www.delftstack.com/ja/howto/react/react-read-csv-file/

**Comment by murakami0000** [comment]
csvファイルのアップロードとダウンロードはできるようになったのでgit に上げました。
元気だったら次の指示ください～
それと西尾君がチームズに質問上げてたよ
